window.promptAtlasData = {
  categories: [
    {
      id: "all",
      name: "All",
      nameZh: "全部",
      description: "Browse every prompt pattern in the library.",
      descriptionZh: "瀏覽整個提示詞資料庫。",
    },
    {
      id: "fundamentals",
      name: "Fundamentals",
      nameZh: "基礎原則",
      description: "Core prompt-writing habits distilled from the guide.",
      descriptionZh: "從指南整理出的提示詞核心寫法。",
    },
    {
      id: "admin",
      name: "Administrative Support",
      nameZh: "行政支援",
      description: "Scheduling, inbox triage, travel planning, and operational prep.",
      descriptionZh: "涵蓋排程、郵件整理、差旅規劃與日常營運支援。",
    },
    {
      id: "communications",
      name: "Communications",
      nameZh: "企業傳訊",
      description: "Press, briefing, spokesperson, and internal messaging workflows.",
      descriptionZh: "涵蓋新聞稿、簡報準備、發言人訓練與內部溝通。",
    },
    {
      id: "customer-service",
      name: "Customer Service",
      nameZh: "客戶服務",
      description: "Reply drafting, issue resolution, feedback analysis, and self-service.",
      descriptionZh: "涵蓋回覆草擬、疑難處理、回饋分析與自助支援。",
    },
    {
      id: "executives",
      name: "Executives",
      nameZh: "管理層",
      description: "High-leverage prompts for fast decisions, presentations, and research.",
      descriptionZh: "幫助管理層快速決策、準備簡報與研究資訊。",
    },
    {
      id: "frontline",
      name: "Frontline Management",
      nameZh: "前線管理",
      description: "Operational prompts for store, site, and shift-based environments.",
      descriptionZh: "適用於門店、現場與輪班管理的實務提示詞。",
    },
    {
      id: "hr",
      name: "Human Resources",
      nameZh: "人力資源",
      description: "Recruiting, onboarding, candidate communication, and people programs.",
      descriptionZh: "涵蓋招聘、入職、候選人溝通與人才發展。",
    },
    {
      id: "marketing",
      name: "Marketing",
      nameZh: "市場行銷",
      description: "Branding, content, audience research, and campaign ideation.",
      descriptionZh: "涵蓋品牌、內容、受眾研究與活動構想。",
    },
    {
      id: "project",
      name: "Project Management",
      nameZh: "專案管理",
      description: "Planning, testing, status reporting, and retrospectives.",
      descriptionZh: "涵蓋規劃、測試、狀態匯報與回顧。",
    },
    {
      id: "sales",
      name: "Sales",
      nameZh: "銷售",
      description: "Discovery, enablement, RFP support, and relationship development.",
      descriptionZh: "涵蓋客戶研究、銷售支援、RFP 與關係經營。",
    },
    {
      id: "small-business",
      name: "Small Business",
      nameZh: "中小企",
      description: "Prompts for owners juggling pricing, marketing, and operations.",
      descriptionZh: "適合身兼多職的老闆處理定價、行銷與營運。",
    },
    {
      id: "startup",
      name: "Startup Leaders",
      nameZh: "初創團隊",
      description: "Strategy, investor storytelling, launch planning, and product direction.",
      descriptionZh: "涵蓋策略、募資敘事、上市計劃與產品方向。",
    },
  ],
  tips: [
    {
      id: "tip-persona",
      title: "Set a persona before the task",
      titleZh: "先定角色，再落任務",
      text: "Start with who Gemini should sound like, then describe the job to do.",
      textZh: "先交代 AI 要扮演甚麼角色，再說明要完成的工作，輸出通常會更貼位。",
    },
    {
      id: "tip-context",
      title: "Add context from real work",
      titleZh: "加入真實工作背景",
      text: "Reference your docs, stakeholders, deadlines, or constraints so the output feels usable.",
      textZh: "把文件、持份者、截止時間或限制加進提示詞，結果會更接近可直接使用的版本。",
    },
    {
      id: "tip-format",
      title: "Ask for the output format",
      titleZh: "直接指定輸出格式",
      text: "Bullets, table, email, outline, and talking points each lead to different results.",
      textZh: "主動指定要清單、表格、電郵、提綱或講稿，會大幅影響最後成品。",
    },
    {
      id: "tip-iterate",
      title: "Refine with follow-up prompts",
      titleZh: "用追問逐步修正",
      text: "Treat prompting as a conversation: simplify, reorganize, translate, or deepen the first draft.",
      textZh: "把提示詞當對話處理，先出初稿，再逐步要求精簡、重組、翻譯或深化。",
    },
  ],
  cards: [
    {
      id: "fundamentals-1",
      category: "fundamentals",
      page: "2-3",
      tools: ["Gmail", "Docs", "Gemini Advanced"],
      title: "Persona + task + context + format",
      titleZh: "角色 + 任務 + 背景 + 格式",
      summary: "A reusable skeleton for writing prompts that sound focused from the first try.",
      summaryZh: "適合做任何提示詞的四格骨架，幫你第一輪已經更清晰。",
      prompt: "Act as a [role]. Create [deliverable] for [audience] using [context or source files]. Format the response as [table, bullets, email, outline].",
      promptZh: "請以[角色]身份，根據[背景／來源文件]為[受眾]製作[交付內容]，並以[表格／重點清單／電郵／提綱]格式輸出。",
      keywords: ["framework", "structure", "format", "context"],
    },
    {
      id: "fundamentals-2",
      category: "fundamentals",
      page: "3",
      tools: ["All apps"],
      title: "Use natural language and specific verbs",
      titleZh: "用自然語言，加上明確動詞",
      summary: "Prompts work better when the action is explicit: summarize, compare, draft, rewrite, organize.",
      summaryZh: "提示詞最好有清楚動詞，例如總結、比較、撰寫、改寫、整理。",
      prompt: "Summarize the main ideas from [topic] and then rewrite them as a short briefing for [audience].",
      promptZh: "先總結[主題]的重點，再改寫成給[受眾]閱讀的簡短 briefing。",
      keywords: ["verbs", "summarize", "rewrite", "clarity"],
    },
    {
      id: "fundamentals-3",
      category: "fundamentals",
      page: "3",
      tools: ["Drive", "Docs", "Gmail"],
      title: "Personalize with your own files",
      titleZh: "用自己文件提升精準度",
      summary: "The guide repeatedly encourages grounding prompts in existing docs and messages.",
      summaryZh: "指南反覆強調：把已有文件、郵件或資料帶入提示詞，效果會更準。",
      prompt: "Use the key points from @[source file] to create a concise update for [audience] with decisions, risks, and next steps.",
      promptZh: "請參考 @[來源文件] 的重點，為[受眾]整理一份包含決策、風險與下一步的簡短更新。",
      keywords: ["files", "source", "grounding", "drive"],
    },
    {
      id: "fundamentals-4",
      category: "fundamentals",
      page: "3,58",
      tools: ["Gemini Advanced"],
      title: "Iterate until the shape is right",
      titleZh: "一路追問到輸出形狀正確為止",
      summary: "One strong first draft plus two precise follow-ups often beats one giant prompt.",
      summaryZh: "與其一次寫超長提示詞，不如先出初稿，再用兩三輪精準追問修好。",
      prompt: "Shorten this by 30 percent, group related ideas, and turn the result into an executive-ready note.",
      promptZh: "把這份內容縮短三成，將相近觀點分組，最後整理成管理層可直接閱讀的備忘錄。",
      keywords: ["iteration", "follow-up", "refine", "editing"],
    },
    {
      id: "admin-1",
      category: "admin",
      page: "7",
      tools: ["Gemini Advanced", "Docs"],
      title: "Build a team offsite agenda",
      titleZh: "規劃團隊 offsite 議程",
      summary: "Useful for turning a rough gathering brief into a multi-day agenda with bonding and strategy time.",
      summaryZh: "把零散想法整理成多日行程，兼顧 team bonding 同策略討論。",
      prompt: "Create a three-day offsite agenda for a newly combined team in [city]. Include team bonding, focused strategy sessions, and a daily recap block.",
      promptZh: "為一支新組成團隊在[城市]設計三日 offsite 議程，包含 team bonding、深度策略討論，以及每日總結時段。",
      keywords: ["agenda", "offsite", "meeting", "planning"],
    },
    {
      id: "admin-2",
      category: "admin",
      page: "8",
      tools: ["Gmail"],
      title: "Triage an executive inbox",
      titleZh: "整理主管郵箱優先次序",
      summary: "Summarize recent messages, surface deadlines, and separate action items from FYIs.",
      summaryZh: "快速整理近期郵件、截止日期，以及真正需要跟進的事項。",
      prompt: "Review emails from [sender or group] over the last [time period]. Summarize urgent requests, deadlines, and decisions in priority order.",
      promptZh: "整理過去[時間範圍]來自[寄件者／群組]的郵件，按優先次序總結緊急要求、截止日與已定決策。",
      keywords: ["inbox", "email", "triage", "deadlines"],
    },
    {
      id: "admin-3",
      category: "admin",
      page: "9",
      tools: ["Sheets", "Docs"],
      title: "Plan business travel and budget",
      titleZh: "規劃商務出差與預算",
      summary: "Combine itinerary planning with travel and entertainment tracking in one workflow.",
      summaryZh: "把行程安排同差旅報銷預算放入同一個工作流程。",
      prompt: "Draft a business travel plan for [trip purpose] covering flights, hotel, local transport, buffer time, and an estimated budget table.",
      promptZh: "為[出差目的]草擬商務行程，包括航班、酒店、本地交通、緩衝時間，以及一份預算表。",
      keywords: ["travel", "budget", "itinerary", "expense"],
    },
    {
      id: "communications-1",
      category: "communications",
      page: "10",
      tools: ["Docs"],
      title: "Draft a press release",
      titleZh: "撰寫新聞稿",
      summary: "Turn product or company updates into a clean announcement with headline, quote, and CTA.",
      summaryZh: "把公司或產品消息整理成完整新聞稿，包括標題、引言與行動呼籲。",
      prompt: "Write a press release announcing [news]. Include a strong headline, a short subheading, one executive quote, and a final paragraph on next steps.",
      promptZh: "為[消息]撰寫新聞稿，包含醒目標題、短副標、一段高層引言，以及說明下一步的結尾段落。",
      keywords: ["press", "announcement", "quote", "pr"],
    },
    {
      id: "communications-2",
      category: "communications",
      page: "11",
      tools: ["Docs", "Gemini Advanced"],
      title: "Prepare briefing notes",
      titleZh: "準備分析師或媒體簡報備忘",
      summary: "Condense background information into a briefing pack with likely questions and approved talking points.",
      summaryZh: "把背景資料濃縮成 briefing pack，附常見問題與建議說法。",
      prompt: "Prepare briefing notes for [spokesperson] before a conversation with [audience]. Include context, likely questions, key messages, and red-flag topics to avoid.",
      promptZh: "為[發言人]準備與[對象]會面的 briefing notes，內容包括背景、可能問題、關鍵信息及應避免的敏感話題。",
      keywords: ["briefing", "analyst", "media", "talking points"],
    },
    {
      id: "communications-3",
      category: "communications",
      page: "12",
      tools: ["Docs", "Meet"],
      title: "Train a spokesperson",
      titleZh: "為發言人做問答演練",
      summary: "Generate interview questions and a sharper internal announcement from the same source material.",
      summaryZh: "可以由同一份資料，生成模擬訪問問題同內部公告版本。",
      prompt: "Generate 12 realistic interview questions about [topic], then propose concise model answers and a confident tone guide for the speaker.",
      promptZh: "就[主題]生成 12 條真實感較高的訪問問題，並提供精簡示範答案與發言語氣建議。",
      keywords: ["spokesperson", "interview", "questions", "internal comms"],
    },
    {
      id: "customer-service-1",
      category: "customer-service",
      page: "13",
      tools: ["Gmail", "Docs"],
      title: "Draft customer replies with empathy",
      titleZh: "撰寫具同理心的客戶回覆",
      summary: "Helpful when you need a response that is calm, clear, and action-oriented.",
      summaryZh: "適合在需要冷靜、清楚又有下一步安排的客戶回覆時使用。",
      prompt: "Draft a reply to a customer about [issue]. Acknowledge the frustration, explain the situation clearly, and end with concrete next steps and timing.",
      promptZh: "就[問題]為客戶草擬回覆：先表示理解，再清楚說明情況，最後列出具體下一步與預計時間。",
      keywords: ["reply", "support", "empathy", "customer email"],
    },
    {
      id: "customer-service-2",
      category: "customer-service",
      page: "14",
      tools: ["Docs", "Drive"],
      title: "Resolve complex issues using FAQs",
      titleZh: "根據 FAQ 處理複雜客訴",
      summary: "A grounded prompt pattern for synthesizing policies, steps, and exceptions from support docs.",
      summaryZh: "可把支援文件、FAQ 與例外情況整合成一致的回應建議。",
      prompt: "Use @[FAQ or policy doc] to answer this customer issue. Separate the response into what we know, what we need to confirm, and the safest next action.",
      promptZh: "請參考 @[FAQ 或政策文件] 回應此客戶問題，分開列出已知資訊、仍需確認事項，以及最穩妥的下一步。",
      keywords: ["faq", "policy", "resolution", "complex issue"],
    },
    {
      id: "customer-service-3",
      category: "customer-service",
      page: "15-16",
      tools: ["Sheets", "Docs"],
      title: "Analyze feedback and self-service gaps",
      titleZh: "分析回饋與自助服務缺口",
      summary: "Spot recurring complaints, group themes, and suggest content customers can use on their own.",
      summaryZh: "找出常見投訴主題，並建議可讓客戶自行解決的內容。",
      prompt: "Review these customer comments and cluster them into themes. Identify the top friction points and recommend self-service content we should create first.",
      promptZh: "請分析這批客戶留言並分組，指出最主要摩擦點，並建議應優先建立哪些自助支援內容。",
      keywords: ["feedback", "analysis", "self-service", "voice of customer"],
    },
    {
      id: "executives-1",
      category: "executives",
      page: "17",
      tools: ["Gmail", "Gemini mobile"],
      title: "Communicate on the go",
      titleZh: "移動中快速處理溝通",
      summary: "Convert voice notes or rough ideas into polished executive emails while traveling.",
      summaryZh: "把零碎語音或短句整理成可直接發出的管理層郵件。",
      prompt: "Turn these rough notes into a brief executive email. Keep the tone calm, decisive, and easy to skim on mobile.",
      promptZh: "把以下零碎筆記整理成簡短管理層電郵，語氣要沉穩、果斷，而且方便手機快速閱讀。",
      keywords: ["mobile", "executive email", "travel", "voice notes"],
    },
    {
      id: "executives-2",
      category: "executives",
      page: "18-19",
      tools: ["Slides", "Docs"],
      title: "Outline a presentation in minutes",
      titleZh: "幾分鐘內起好簡報大綱",
      summary: "Ideal for converting a leadership topic into a crisp narrative structure.",
      summaryZh: "適合把管理層主題快速轉成條理清晰的簡報故事線。",
      prompt: "Create a presentation outline for [topic] aimed at [audience]. Include an opening narrative, 3 key arguments, supporting evidence, and a closing recommendation.",
      promptZh: "為[主題]建立給[受眾]使用的簡報大綱，包含開場鋪陳、3 個核心論點、支持證據與結尾建議。",
      keywords: ["presentation", "outline", "slides", "leadership"],
    },
    {
      id: "executives-3",
      category: "executives",
      page: "20-22",
      tools: ["Gemini Advanced", "Docs", "Sheets"],
      title: "Research trends and competitors",
      titleZh: "研究趨勢與競爭對手",
      summary: "Blend market scans, technology trends, competitor summaries, and vendor research into one executive workflow.",
      summaryZh: "把市場掃描、科技趨勢、競品整理與供應商研究整合成一套高層工作流程。",
      prompt: "Summarize the latest shifts in [market]. Compare 3 competitors, call out opportunities and risks, and finish with recommendations for executive discussion.",
      promptZh: "總結[市場]最新變化，比較 3 個競爭對手，指出機會與風險，最後附上供管理層討論的建議。",
      keywords: ["market research", "competitor", "technology trends", "vendors"],
    },
    {
      id: "frontline-1",
      category: "frontline",
      page: "24",
      tools: ["Gemini mobile", "Docs"],
      title: "Find the right answer fast",
      titleZh: "快速找到正確答案",
      summary: "Helpful for sales floor or site teams who need policy or promotion information instantly.",
      summaryZh: "適合前線同事在門店或現場即時查詢政策、活動或產品資訊。",
      prompt: "Using the documents linked here, answer this customer question clearly and in plain language. Include any limits, exceptions, or escalation steps.",
      promptZh: "請根據這些文件，以簡單直接方式回答客戶問題，並列出限制、例外情況或需要升級處理的步驟。",
      keywords: ["policy lookup", "frontline", "customer answer", "quick info"],
    },
    {
      id: "frontline-2",
      category: "frontline",
      page: "25",
      tools: ["Sheets", "Tasks"],
      title: "Streamline team task management",
      titleZh: "整理前線團隊任務",
      summary: "Turn scattered updates into a practical action list with ownership and due dates.",
      summaryZh: "把零散更新變成有負責人、有期限的可執行清單。",
      prompt: "Organize these team updates into a task tracker. Group by priority, assign suggested owners, and highlight blockers that need manager attention.",
      promptZh: "把這些團隊更新整理成任務追蹤表，按優先次序分類，建議負責人，並標示需要主管介入的阻塞點。",
      keywords: ["task tracker", "team collaboration", "operations", "ownership"],
    },
    {
      id: "frontline-3",
      category: "frontline",
      page: "26",
      tools: ["Sheets"],
      title: "Watch inventory and audit readiness",
      titleZh: "追蹤庫存與審核準備",
      summary: "Useful for spotting shortages, discrepancies, and missing process checks before they escalate.",
      summaryZh: "可提前發現缺貨、數據不一致或流程檢查遺漏。",
      prompt: "Review this inventory or audit sheet and flag unusual patterns, possible compliance gaps, and the top actions to take this week.",
      promptZh: "請檢視這份庫存或審核表，標示異常模式、可能合規缺口，以及本週最應優先處理的行動。",
      keywords: ["inventory", "audit", "compliance", "operations"],
    },
    {
      id: "hr-1",
      category: "hr",
      page: "27-28",
      tools: ["Docs", "Sheets"],
      title: "Welcome and recruit with consistency",
      titleZh: "用一致方式迎新與招聘",
      summary: "Create onboarding messages, recruiting updates, and metrics summaries without starting from scratch.",
      summaryZh: "可快速建立迎新內容、招聘更新與招聘數據摘要。",
      prompt: "Draft a welcome package for a new employee joining [team]. Include a warm note, first-week agenda, and the key people or resources they should know.",
      promptZh: "為加入[團隊]的新員工草擬 welcome package，包含歡迎訊息、第一週行程，以及應認識的重要人物與資源。",
      keywords: ["onboarding", "recruiting", "welcome", "metrics"],
    },
    {
      id: "hr-2",
      category: "hr",
      page: "29",
      tools: ["Docs", "Gmail"],
      title: "Run structured interviews",
      titleZh: "建立結構化面試流程",
      summary: "Generate fair interview questions and cleaner communication for candidates.",
      summaryZh: "產出更一致、公平的面試問題，亦方便整理候選人溝通內容。",
      prompt: "Create a structured interview guide for a [role] candidate. Include 8 questions, what strong answers look like, and a short follow-up email template.",
      promptZh: "為[職位]候選人建立結構化面試指引，包含 8 條問題、優秀答案特徵，以及簡短 follow-up 電郵範本。",
      keywords: ["interview", "candidate", "guide", "communication"],
    },
    {
      id: "hr-3",
      category: "hr",
      page: "30-31",
      tools: ["Sheets", "Forms", "Docs"],
      title: "Measure engagement and follow up",
      titleZh: "量度投入度並安排後續",
      summary: "Summarize survey data, identify themes, and turn findings into people actions.",
      summaryZh: "總結員工調查數據、找出主題，再轉化為實際的人才行動。",
      prompt: "Analyze these employee survey results. Highlight the strongest positive themes, the biggest concerns, and 3 practical follow-up actions for managers.",
      promptZh: "請分析這批員工調查結果，指出最明顯的正面主題、最大憂慮，以及經理人可跟進的 3 個實際行動。",
      keywords: ["engagement", "survey", "learning plan", "hr insights"],
    },
    {
      id: "marketing-1",
      category: "marketing",
      page: "32-33",
      tools: ["Slides", "Docs", "Image generation"],
      title: "Shape visual identity and brand strategy",
      titleZh: "建立視覺識別與品牌策略",
      summary: "Great for logo direction, positioning statements, and partnership ideas.",
      summaryZh: "適合發想 logo 方向、品牌定位與合作提案。",
      prompt: "Develop a simple brand direction for [business]. Define tone, visual cues, target audience, and 3 partnership ideas that fit the brand.",
      promptZh: "為[品牌／業務]建立基礎品牌方向：定義語氣、視覺元素、目標受眾，以及 3 個合適的合作構想。",
      keywords: ["brand", "identity", "partnership", "visual"],
    },
    {
      id: "marketing-2",
      category: "marketing",
      page: "34-36",
      tools: ["Docs", "Sheets"],
      title: "Research audiences and market trends",
      titleZh: "研究市場趨勢與受眾",
      summary: "A flexible pattern for personas, trend scans, and message-market fit work.",
      summaryZh: "適合建立 persona、整理市場趨勢，以及測試訊息與市場契合度。",
      prompt: "Create an audience brief for [segment]. Include demographics, motivations, friction points, preferred channels, and the messages most likely to resonate.",
      promptZh: "為[受眾群]建立 audience brief，包含人口特徵、動機、痛點、常用渠道，以及最可能打動他們的信息。",
      keywords: ["audience", "persona", "market research", "sem"],
    },
    {
      id: "marketing-3",
      category: "marketing",
      page: "37-39",
      tools: ["Docs", "Slides", "Image generation"],
      title: "Create campaigns and social content",
      titleZh: "建立 campaign 與社交內容",
      summary: "Generate campaign concepts, ad visuals, blog angles, and post copy at speed.",
      summaryZh: "快速產生 campaign 主題、廣告視覺、部落格方向與社交貼文文案。",
      prompt: "Build a mini campaign for [offer]. Provide a campaign idea, 3 ad concepts, 5 social post angles, and one blog headline with a short summary.",
      promptZh: "為[產品／優惠]建立 mini campaign：提供 campaign 主題、3 個廣告概念、5 個社交貼文角度，以及 1 個 blog 標題和摘要。",
      keywords: ["campaign", "social media", "blog", "creative"],
    },
    {
      id: "project-1",
      category: "project",
      page: "40",
      tools: ["Sheets", "Docs"],
      title: "Generate user acceptance tests",
      titleZh: "生成 UAT 測試案例",
      summary: "Turn feature requirements into realistic user acceptance scenarios and edge cases.",
      summaryZh: "把功能需求轉成真實 UAT 情景與邊界測試案例。",
      prompt: "Using this feature summary, create user acceptance test cases with preconditions, steps, expected results, and edge cases.",
      promptZh: "請根據這份功能摘要生成 UAT 測試案例，列出前置條件、步驟、預期結果及邊界情況。",
      keywords: ["uat", "testing", "requirements", "qa"],
    },
    {
      id: "project-2",
      category: "project",
      page: "41",
      tools: ["Docs", "Slides"],
      title: "Report status and run retrospectives",
      titleZh: "匯報專案狀態與做回顧",
      summary: "Useful for stakeholder updates and honest team reflection after a milestone.",
      summaryZh: "既適合向持份者匯報，也適合里程碑後做團隊回顧。",
      prompt: "Summarize this project update for executives. Cover progress, risks, decisions needed, and the overall confidence level in a short format.",
      promptZh: "請把這份專案更新整理成給管理層閱讀的簡短摘要，涵蓋進度、風險、待決事項，以及整體信心程度。",
      keywords: ["status report", "retrospective", "stakeholder update", "risks"],
    },
    {
      id: "project-3",
      category: "project",
      page: "42",
      tools: ["Sheets", "Docs"],
      title: "Track issues and build a workback plan",
      titleZh: "追蹤問題與建立倒排時程",
      summary: "Convert a messy launch or initiative into sequenced tasks with dependencies.",
      summaryZh: "把混亂的 launch 或專案拆成有依賴關係的倒排任務。",
      prompt: "Create a workback schedule for [launch or milestone]. List key tasks, dependencies, owners, and the warning signs that would put the date at risk.",
      promptZh: "為[上市／里程碑]建立倒排時程，列出關鍵任務、依賴關係、負責人，以及可能拖慢日期的預警訊號。",
      keywords: ["workback", "schedule", "issue tracker", "dependencies"],
    },
    {
      id: "sales-1",
      category: "sales",
      page: "43-44",
      tools: ["Docs", "Gemini Advanced"],
      title: "Research customers and journeys",
      titleZh: "研究客戶與購買旅程",
      summary: "Ideal for discovery prep, customer insight summaries, and journey mapping.",
      summaryZh: "適合做客戶 discovery 前準備、客戶洞察整理與旅程地圖。",
      prompt: "Create a customer research brief for [account or segment]. Include likely goals, pain points, buying triggers, objections, and a simple journey map.",
      promptZh: "為[客戶帳戶／群組]建立 research brief，包含目標、痛點、購買誘因、常見疑慮，以及簡單客戶旅程圖。",
      keywords: ["customer research", "journey", "discovery", "account planning"],
    },
    {
      id: "sales-2",
      category: "sales",
      page: "45-47",
      tools: ["Docs", "Gmail"],
      title: "Handle RFPs and sales enablement",
      titleZh: "處理 RFP 與銷售支援",
      summary: "Organize request responses, enable the sales team, and tailor assets for specific prospects.",
      summaryZh: "用於整理 RFP 回應、支援銷售團隊，並為特定客戶訂製資產。",
      prompt: "Draft an outline for responding to this RFP. Group the requirements, identify missing information, and suggest assets that would strengthen the response.",
      promptZh: "為這份 RFP 草擬回應大綱，先分組需求，指出缺失資訊，並建議可加強提案的相關資產。",
      keywords: ["rfp", "enablement", "proposal", "custom asset"],
    },
    {
      id: "sales-3",
      category: "sales",
      page: "48-49",
      tools: ["Meet", "Docs", "Gmail"],
      title: "Prepare calls and nurture relationships",
      titleZh: "準備會議與經營客戶關係",
      summary: "Great for call planning, follow-up outreach, and customer appreciation moments.",
      summaryZh: "適合準備客戶會議、跟進外聯以及客戶答謝內容。",
      prompt: "Prepare me for a 30-minute customer call with [company]. Include discovery questions, a suggested flow, likely objections, and a concise follow-up email draft.",
      promptZh: "幫我準備與[公司]進行的 30 分鐘客戶會議，包含 discovery 問題、建議流程、可能異議，以及一封簡短跟進電郵草稿。",
      keywords: ["customer call", "follow-up", "relationship", "objections"],
    },
    {
      id: "small-business-1",
      category: "small-business",
      page: "50",
      tools: ["Sheets"],
      title: "Compare pricing options",
      titleZh: "比較定價方案",
      summary: "Useful when owners need a quick pricing table with trade-offs and positioning notes.",
      summaryZh: "適合中小企老闆快速比較價位、差異與定位。",
      prompt: "Build a pricing comparison for [product or service]. Show tiers, included features, profit considerations, and who each tier is best for.",
      promptZh: "請為[產品／服務]建立定價比較表，列出方案層級、包含功能、利潤考量，以及每個方案最適合哪類客戶。",
      keywords: ["pricing", "comparison", "tiers", "small business"],
    },
    {
      id: "small-business-2",
      category: "small-business",
      page: "51-53",
      tools: ["Docs", "Sheets", "Gmail"],
      title: "Balance productivity, marketing, and operations",
      titleZh: "兼顧效率、行銷與營運",
      summary: "A mixed workflow for owners handling personal productivity, content ideas, and policy administration.",
      summaryZh: "適合一人身兼多職時，同步處理效率、內容構想與行政政策。",
      prompt: "Help me prioritize this week as a small business owner. Organize tasks into revenue, operations, people, and marketing, then suggest what to delegate or defer.",
      promptZh: "請幫我以小企業老闆身份安排本週優先事項，把任務分成收入、營運、人事與行銷，並建議哪些可委派或延後。",
      keywords: ["productivity", "marketing", "operations", "time off"],
    },
    {
      id: "small-business-3",
      category: "small-business",
      page: "56",
      tools: ["Docs", "Sheets"],
      title: "Negotiate with vendors and control budgets",
      titleZh: "與供應商談判並控管預算",
      summary: "Turn cost pressure into a more structured vendor conversation and budget plan.",
      summaryZh: "把成本壓力轉化成更有條理的供應商溝通與預算安排。",
      prompt: "Draft a vendor negotiation plan for [service]. Include desired terms, fallback positions, budget limits, and a professional email opening.",
      promptZh: "為[服務]草擬供應商談判計劃，列出理想條件、退讓底線、預算上限，以及專業的開場電郵。",
      keywords: ["vendor", "negotiation", "budget", "cost control"],
    },
    {
      id: "startup-1",
      category: "startup",
      page: "54-55",
      tools: ["Gemini Advanced", "Docs"],
      title: "Clarify business strategy and pitch",
      titleZh: "梳理商業策略與 pitch",
      summary: "A flexible prompt for refining positioning, elevator pitches, and founder messaging.",
      summaryZh: "適合整理定位、電梯簡報與創辦人對外說法。",
      prompt: "Help me sharpen our startup strategy. Summarize the problem we solve, who we serve, why now, and turn that into a 45-second elevator pitch.",
      promptZh: "請幫我整理 startup 策略：總結我們解決甚麼問題、服務誰、為甚麼是現在，並轉成一段 45 秒電梯簡報。",
      keywords: ["strategy", "pitch", "founder", "personal brand"],
    },
    {
      id: "startup-2",
      category: "startup",
      page: "52,57",
      tools: ["Docs", "Slides"],
      title: "Prepare investors and product launch plans",
      titleZh: "準備募資與產品推出計劃",
      summary: "Blend investor-facing storytelling with launch messaging and milestone planning.",
      summaryZh: "把募資敘事、上市訊息與里程碑規劃整合起來。",
      prompt: "Create a startup launch plan for [product]. Include launch phases, core messaging, risks, success metrics, and what investors would care about most.",
      promptZh: "為[產品]建立 startup launch plan，包含推出階段、核心信息、風險、成功指標，以及投資者最關心的重點。",
      keywords: ["launch", "investor", "fundraising", "product"],
    },
    {
      id: "startup-3",
      category: "startup",
      page: "57",
      tools: ["Sheets", "Docs"],
      title: "Turn vision into roadmap",
      titleZh: "把願景轉成 roadmap",
      summary: "Useful when a founder needs to move from ambitious ideas into sequenced execution.",
      summaryZh: "適合創辦人把較抽象的產品願景拆解成可執行路線圖。",
      prompt: "Turn this product vision into a 2-quarter roadmap. Group initiatives by impact, effort, dependencies, and what we should validate first.",
      promptZh: "請把這份產品願景轉成兩季 roadmap，按影響力、投入程度、依賴關係，以及應先驗證的假設來分組。",
      keywords: ["roadmap", "product strategy", "validation", "execution"],
    },
  ],
};
